---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

# - Developer:
#     - Github:
#         - abbr: GH
#           href: https://github.com/

# - Social:
#     - Reddit:
#         - abbr: RE
#           href: https://reddit.com/

# - Entertainment:
#     - YouTube:
#         - abbr: YT
#           href: https://youtube.com/
- HomeLab:
    - Unifi Gateway:
        - icon: unifi.png
          href: https://unifi.home.eltimn.com/
    - ntfy.sh:
        - icon: ntfy.png
          href: https://ntfy.home.eltimn.com/
    - Channels DVR:
        - icon: channels.png
          href: https://dvr.home.eltimn.com/
    - Jellyfin:
        - icon: jellyfin.png
          href: https://jellyfin.home.eltimn.com/
